# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_modifiergroup_modifieroption_recipe_recipeingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=120)),
                ('experience_level', models.CharField(max_length=80)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=80)),
                ('portfolio_url', models.URLField(blank=True)),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(upload_to='job_applications/cvs/')),
                ('agreed_to_policy', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
