# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(default='footer', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
