# Generated by hand

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0002_alter_salaryrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrecord',
            name='payment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salaryrecord',
            name='status',
            field=models.CharField(
                choices=[
                    ('paid', 'Paid'),
                    ('pending', 'Pending'),
                    ('processing', 'Processing'),
                ],
                default='pending',
                max_length=20,
                db_index=True,
            ),
        ),
    ]
